[package]
name = "jameboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
eframe = "0.22.0"
egui = "0.22.0"
egui_extras = "0.22.0"
